### ISSUE TITLE
Chocolatey out of date, v2.36.6 needed

### ISSUE THREAD

**Issue by spedersen-emailage** [Versent/saml2aws#1037]
The [Chocolatey package](https://community.chocolatey.org/packages/saml2aws) is behind two revisions. It's at 2.36.4 while release is 2.36.6. There is a [critical Azure AD fix](https://github.com/Versent/saml2aws/commit/5ec150897b5b10eb36e99103caeeadc3ae1d5aa7) in 2.36.6. For now, I've instructed our people to [install via the .msi](https://github.com/Versent/saml2aws/releases/download/v2.36.6/saml2aws_2.36.6_windows_amd64.msi).

Is the Chocolatey package maintained officially? If not, is there any way to have an official package to ensure it's in sync w/ the most current release?

Several others have commented on its status in the last month.

Not sure how the [Homebrew formula](https://formulae.brew.sh/formula/saml2aws) is maintained, but it's current.

**Comment by spedersen-emailage** [comment]
@davidobrien1985?
@wolfeidau?

**Comment by spedersen-emailage** [comment]
Any idea when Chocolately will be in sync?

**Comment by gliptak** [comment]
#985

**Comment by mapkon** [comment]
@briantist Can you help with this?

**Comment by briantist** [comment]
sorry @mapkon , as I [mentioned here](https://github.com/Versent/saml2aws/discussions/1011#discussioncomment-5587276) I don't use the chocolately package and don't know anything generating one.

**Comment by mendhak** [comment]
I'm not familiar with Appveyor, but I do see an [Appveyor YML](https://github.com/Versent/saml2aws/blob/master/.appveyor/appveyor.yml) file that has a 'choco push' command at the end. Would this mean there's an AppVeyor build somewhere that isn't running, and who manages that Appveyor accountt?

That said, long term, gliptak's [comment](https://github.com/Versent/saml2aws/issues/985) makes sense since it could move the choco management right into Github Actions which is more visible/debuggable/maintainable.

**Comment by mendhak** [comment]
Alternate is to use scoop, I believe they are building off the releases in this repo so it's the latest. 

https://scoop.sh/#/apps?q=saml2aws

```powershell
# Powershell
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser 
irm get.scoop.sh | iex
scoop install saml2aws
```

**Comment by nascosto** [comment]
This has been fixed. Latest version is correct on Chocolatey: https://community.chocolatey.org/packages/saml2aws

**Comment by tinaboyce** [comment]
Thanks for the head's up @nascosto , I'll close this issue.
