### ISSUE TITLE
Add support for shell completion

### ISSUE THREAD

**Issue by AjayKMehta** [Versent/saml2aws#631]
Thank you for developing this! Would it be possible to add shell completion?

**Comment by sledigabel** [comment]
I was reading up on the [kingpin documentation](https://pkg.go.dev/gopkg.in/alecthomas/kingpin.v2#readme-reference-documentation) (which saml2aws uses to back the cli) and it seems to be already supported.

```bash
./saml2aws --completion-script-zsh  # replace here your shell name
```

As far as I can see, it's working with `bash` and `zsh`, not sure about the rest.
I'll add a quick PR to add up on the documentation about it.

**Comment by sledigabel** [comment]
Tested it on, it works great :-) I'm glad I looked into it
Filed PR https://github.com/Versent/saml2aws/pull/636

**Comment by AjayKMehta** [comment]
Thanks @sledigabel. I was hoping for PowerShell support but it seems [kingpin](https://github.com/alecthomas/kingpin) only works with `bash` and `zsh`.

On another note, `kingpin` seems to be in maintenance mode as the last release was back in 2015 and the creator has created a successor project called `kong`. There is another popular Go CLI library that a lot of projects use that does offer shell completion for a bunch of shells including PowerShell: [`cobra`](https://github.com/spf13/cobra).

If I knew Go, I would submit a PR to use it 😄

**Comment by sledigabel** [comment]
Yes indeed,
Back on that question I had a look at kingpin and cobra (which I'm using on other projects), the only challenge that I see is the native overriding with all the environment variables that seem specific to kingpin.

Because of this alone it is not going to be just a find/replace,
Having said that I still think replacing kingpin and staying future proof is the right approach.

Similarly, looking at viper to handle the config file but viper doesn't handle ini files natively.

**Comment by sledigabel** [comment]
@wolfeidau any thoughts on this?

**Comment by sledigabel** [comment]
Had a look again at Kong, it's actually interesting. It seems to tackle the cli from a marshalling stand point.

Quite a significant refactoring, but it could be interesting.
